trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@2
    inputs:
      version: '16.x'

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npm run build
    displayName: 'Build Project'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'dist/'
      artifact: 'drop'
